package com.bezkoder.spring.datajpa.model;

public enum ERole {
	ROLE_CLIENT,
    ROLE_GESTIONNAIRE_CLIENTELE,
    ROLE_GESTIONNAIRE_PATRIMOINE,
    ROLE_CONSEILLER_CLIENTELE,
    ROLE_CONTROLEUR_GESTION,
    ROLE_DIRECTEUR_FINANCIER,
    ROLE_EMPLOYE_CAP,
    ROLE_CHARGE_ETUDE,
    ROLE_PERSONNEL_RH,
    ROLE_DECIDEUR,
    ROLE_MEMBRE_DIRECTOIRE   
}